<?php
    $pathName = pathinfo($_SERVER['PHP_SELF']);
?>
<div id="page-container">
        <!-- BEGIN SIDEBAR -->
        <nav id="page-leftbar" role="navigation">
            <!-- BEGIN SIDEBAR MENU -->
            <ul class="acc-menu" id="sidebar">
                <li><a href="../view/inicio.php"><i class="fa fa-flag-checkered"></i> <span>Início</span></a></li>
                <li class="<?php echo ($pathName['basename'] == 'cadastro_cargo_funcionario.php' || $pathName['basename'] == 'cadastro_cargo_funcionario_alterar.php' || $pathName['basename'] == 'visualizar_cargo.php' || $pathName['basename'] == 'visualizar_cargo_2.php' || $pathName['basename'] == 'permissoes_cargos.php' || $pathName['basename'] == 'visualizar_cliente.php' || $pathName['basename'] == 'cadastro_cliente.php' || $pathName['basename'] == 'atualizar_cliente.php' || $pathName['basename'] == 'visualizar_cliente_2.php' || $pathName['basename'] == 'visualizar_tipos.php' || $pathName['basename'] == 'visualizar_tipo_2.php' || $pathName['basename'] == 'atualizar_tipo.php' || $pathName['basename'] == 'cadastro_tipo.php' || $pathName['basename'] == 'visualizar_segmentos.php' || $pathName['basename'] == 'visualizar_segmento_2.php' || $pathName['basename'] == 'atualizar_segmento.php' || $pathName['basename'] == 'cadastro_segmento.php' || $pathName['basename'] == 'visualizar_galerias_videos.php' || $pathName['basename'] == 'visualizar_galerias_videos_2.php' || $pathName['basename'] == 'atualizar_galerias_videos.php' || $pathName['basename'] == 'cadastro_galerias_videos.php' || $pathName['basename'] == 'cadastro_galerias.php' || $pathName['basename'] == 'atualizar_galerias.php' || $pathName['basename'] == 'visualizar_galerias_2.php') ? 'active' : ''; ?>"><a href="javascript:;"><i class="fa fa-list"></i> <span>Cadastro</span> </a>
                    <ul class="acc-menu" style="<?php echo ($pathName['basename'] == 'cadastro_cargo_funcionario.php' || $pathName['basename'] == 'cadastro_cargo_funcionario_alterar.php' || $pathName['basename'] == 'visualizar_cargo.php' || $pathName['basename'] == 'visualizar_cargo_2.php' || $pathName['basename'] == 'permissoes_cargos.php' || $pathName['basename'] == 'visualizar_cliente.php' || $pathName['basename'] == 'cadastro_cliente.php' || $pathName['basename'] == 'atualizar_cliente.php' || $pathName['basename'] == 'visualizar_cliente_2.php' || $pathName['basename'] == 'visualizar_tipos.php' || $pathName['basename'] == 'visualizar_tipo_2.php' || $pathName['basename'] == 'atualizar_tipo.php' || $pathName['basename'] == 'cadastro_tipo.php' || $pathName['basename'] == 'visualizar_segmentos.php' || $pathName['basename'] == 'visualizar_segmento_2.php' || $pathName['basename'] == 'atualizar_segmento.php' || $pathName['basename'] == 'cadastro_segmento.php' || $pathName['basename'] == 'visualizar_galerias_videos.php' || $pathName['basename'] == 'visualizar_galerias_videos_2.php' || $pathName['basename'] == 'atualizar_galerias_videos.php' || $pathName['basename'] == 'cadastro_galerias_videos.php' || $pathName['basename'] == 'cadastro_galerias.php' || $pathName['basename'] == 'atualizar_galerias.php' || $pathName['basename'] == 'visualizar_galerias_2.php') ? 'display:block;' : ''; ?>">
                        <li class="<?php echo ($pathName['basename'] == 'cadastro_cargo_funcionario.php' || $pathName['basename'] == 'cadastro_cargo_funcionario_alterar.php' || $pathName['basename'] == 'visualizar_cargo.php' || $pathName['basename'] == 'visualizar_cargo_2.php' || $pathName['basename'] == 'permissoes_cargos.php' ) ? 'active' : ''; ?>"><a href="cadastro_cargo_funcionario.php"><i class="fa fa-tasks"></i><span>Cargos</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_cliente.php' || $pathName['basename'] == 'visualizar_cliente_2.php' || $pathName['basename'] == 'atualizar_cliente.php' || $pathName['basename'] == 'cadastro_cliente.php')? 'active' : ''; ?>"><a href="visualizar_cliente.php"><i class="fa fa-group"></i><span>Clientes</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_artigo.php' || $pathName['basename'] == 'visualizar_artigo_2.php' || $pathName['basename'] == 'atualizar_artigo.php' || $pathName['basename'] == 'cadastro_artigo.php')? 'active' : ''; ?>"><a href="visualizar_artigo.php"><i class="fa fa-edit"></i><span>Artigo</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_autor.php' || $pathName['basename'] == 'visualizar_autor_2.php' || $pathName['basename'] == 'atualizar_autor.php' || $pathName['basename'] == 'cadastro_autor.php')? 'active' : ''; ?>"><a href="visualizar_autor.php"><i class="fa fa-user"></i><span>Autores</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_galerias.php' || $pathName['basename'] == 'visualizar_galerias_2.php' || $pathName['basename'] == 'atualizar_galerias.php' || $pathName['basename'] == 'cadastro_galerias.php')? 'active' : ''; ?>"><a href="visualizar_galerias.php"><i class="fa fa-camera"></i><span>Galerias</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_galerias_videos.php' || $pathName['basename'] == 'visualizar_galerias_videos_2.php' || $pathName['basename'] == 'atualizar_galerias_videos.php' || $pathName['basename'] == 'cadastro_galerias_videos.php')? 'active' : ''; ?>"><a href="visualizar_galerias_videos.php"><i class="fa fa-video-camera"></i><span>Galerias Vídeos</span></a></li>
                         <li class="<?php echo ($pathName['basename'] == 'visualizar_segmentos.php' || $pathName['basename'] == 'visualizar_segmento_2.php' || $pathName['basename'] == 'atualizar_segmento.php' || $pathName['basename'] == 'cadastro_segmento.php')? 'active' : ''; ?>"><a href="visualizar_segmentos.php"><i class="fa fa-tag"></i><span>Segmentos</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_tipos.php' || $pathName['basename'] == 'visualizar_tipo_2.php' || $pathName['basename'] == 'atualizar_tipo.php' || $pathName['basename'] == 'cadastro_tipo.php')? 'active' : ''; ?>"><a href="visualizar_tipos.php"><i class="fa fa-rocket"></i><span>Tipos</span></a></li>
                       

                        
                    </ul>
                </li>
                <li class="<?php echo ($pathName['basename'] == 'visualizar_anuncios.php' || $pathName['basename'] == 'cadastro_anuncio.php' || $pathName['basename'] == 'atualizar_anuncio.php' || $pathName['basename'] == 'visualizar_banner_tarja.php' || $pathName['basename'] == 'cadastro_banner_tarja.php' || $pathName['basename'] == 'atualizar_banner_tarja.php' || $pathName['basename'] == 'visualizar_banner_fixo.php' || $pathName['basename'] == 'cadastro_banner_fixo.php' || $pathName['basename'] == 'atualizar_banner_fixo.php' || $pathName['basename'] == 'visualizar_ultimas_noticias.php' || $pathName['basename'] == 'cadastro_ultimas_noticias.php' || $pathName['basename'] == 'atualizar_ultimas_noticias.php') ? 'active' : ''; ?>"><a href="javascript:;"><i class="fa fa-list"></i> <span>Editoriais</span> </a>
                    <ul class="acc-menu" style="<?php echo ($pathName['basename'] == 'visualizar_anuncios.php' || $pathName['basename'] == 'cadastro_anuncio.php' || $pathName['basename'] == 'atualizar_anuncio.php' || $pathName['basename'] == 'visualizar_banner_tarja.php' || $pathName['basename'] == 'cadastro_banner_tarja.php' || $pathName['basename'] == 'atualizar_banner_tarja.php' || $pathName['basename'] == 'visualizar_banner_fixo.php' || $pathName['basename'] == 'cadastro_banner_fixo.php' || $pathName['basename'] == 'atualizar_banner_fixo.php' || $pathName['basename'] == 'visualizar_ultimas_noticias.php' || $pathName['basename'] == 'cadastro_ultimas_noticias.php' || $pathName['basename'] == 'atualizar_ultimas_noticias.php') ? 'display:block;' : ''; ?>">
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_anuncios.php' || $pathName['basename'] == 'cadastro_anuncio.php' || $pathName['basename'] == 'atualizar_anuncio.php') ? 'active' : ''; ?>"><a href="visualizar_anuncios.php"><i class="fa fa-file"></i><span>Anúncios</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_banner_tarja.php' || $pathName['basename'] == 'cadastro_banner_tarja.php' || $pathName['basename'] == 'atualizar_banner_tarja.php') ? 'active' : ''; ?>"><a href="visualizar_banner_tarja.php"><i class="fa fa-ticket"></i><span>Banner Tarja</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_banner_fixo.php' || $pathName['basename'] == 'cadastro_banner_fixo.php' || $pathName['basename'] == 'atualizar_banner_fixo.php') ? 'active' : ''; ?>"><a href="visualizar_banner_fixo.php"><i class="fa fa-square"></i><span>Banner Fixo</span></a></li>
                        <li class="<?php echo ($pathName['basename'] == 'visualizar_ultimas_noticias.php' || $pathName['basename'] == 'cadastro_ultimas_noticias.php' || $pathName['basename'] == 'atualizar_ultimas_noticias.php') ? 'active' : ''; ?>"><a href="visualizar_ultimas_noticias.php"><i class="fa fa-eye"></i><span>Últimas Notícias</span></a></li>
                    </ul>
                </li>                 
                           
            </ul>
            <!-- END SIDEBAR MENU -->
        </nav>
        